-- MySQL Script generated by MySQL Workbench
-- 09/08/17 18:13:19
-- Model: gg_database    Version: 4.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema DB3087534
-- -----------------------------------------------------
USE `DB3087534` ;

-- -----------------------------------------------------
-- Table `DB3087534`.`gg_User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB3087534`.`gg_User` ;

CREATE TABLE IF NOT EXISTS `DB3087534`.`gg_User` (
  `User_ID` INT NOT NULL AUTO_INCREMENT,
  `Created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `Login_Name` VARCHAR(45) NOT NULL,
  `Pwd_Hash` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Zip_Code` VARCHAR(255) NOT NULL,
  `Fon` VARCHAR(255) NULL,
  `Adress` VARCHAR(255) NULL,
  `Picture` VARCHAR(255) NULL,
  `Visibility_Flags` VARCHAR(255) NULL DEFAULT 'EMAIL:0-FON:0-ADRESS:0-PICTURE:0',
  UNIQUE INDEX `Login_Name_UNIQUE` (`Login_Name` ASC),
  INDEX `Login_Name_IND` (`Login_Name` ASC),
  INDEX `Email_IND` (`Email` ASC),
  INDEX `Zip_Code_IND` (`Zip_Code` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Login_Name` ASC, `Email` ASC),
  PRIMARY KEY (`User_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB3087534`.`gg_Interest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB3087534`.`gg_Interest` ;

CREATE TABLE IF NOT EXISTS `DB3087534`.`gg_Interest` (
  `User_ID` INT NOT NULL,
  `Present_ID` INT NOT NULL,
  PRIMARY KEY (`User_ID`, `Present_ID`),
  INDEX `User_IND` (`User_ID` ASC),
  INDEX `Present_IND` (`Present_ID` ASC),
  CONSTRAINT `FK_USER_INTEREST`
    FOREIGN KEY (`User_ID`)
    REFERENCES `DB3087534`.`gg_User` (`User_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB3087534`.`gg_Demand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB3087534`.`gg_Demand` ;

CREATE TABLE IF NOT EXISTS `DB3087534`.`gg_Demand` (
  `User_ID` INT NOT NULL,
  `Present_ID` INT NOT NULL,
  PRIMARY KEY (`User_ID`, `Present_ID`),
  INDEX `User_IND` (`User_ID` ASC),
  INDEX `Present_IND` (`Present_ID` ASC),
  CONSTRAINT `FK_USER_DEMAND`
    FOREIGN KEY (`User_ID`)
    REFERENCES `DB3087534`.`gg_User` (`User_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB3087534`.`gg_Offer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB3087534`.`gg_Offer` ;

CREATE TABLE IF NOT EXISTS `DB3087534`.`gg_Offer` (
  `User_ID` INT NOT NULL,
  `Present_ID` INT NOT NULL,
  PRIMARY KEY (`User_ID`, `Present_ID`),
  INDEX `User_IND` (`User_ID` ASC),
  INDEX `Present_IND` (`Present_ID` ASC),
  CONSTRAINT `FK_USER_OFFER`
    FOREIGN KEY (`User_ID`)
    REFERENCES `DB3087534`.`gg_User` (`User_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB3087534`.`gg_Present`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB3087534`.`gg_Present` ;

CREATE TABLE IF NOT EXISTS `DB3087534`.`gg_Present` (
  `Present_ID` INT NOT NULL AUTO_INCREMENT,
  `Owner_ID` INT NOT NULL,
  `Created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `Title` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(32000) NOT NULL,
  `State` VARCHAR(255) NOT NULL DEFAULT 'Vorhanden',
  `Available_until` DATETIME NULL,
  `Picture` VARCHAR(255) NULL,
  PRIMARY KEY (`Present_ID`, `Owner_ID`),
  FULLTEXT INDEX `Description_TXT` (`Description` ASC),
  INDEX `Title_IND` (`Title` ASC),
  INDEX `Available_until_IND` (`Available_until` ASC),
  INDEX `State_IND` (`State` ASC),
  FULLTEXT INDEX `Title_TXT` (`Title` ASC),
  INDEX `Owner_IND` (`Owner_ID` ASC),
  CONSTRAINT `FK_OWNER_PRESENT`
    FOREIGN KEY (`Owner_ID`)
    REFERENCES `DB3087534`.`gg_User` (`User_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_INTEREST_PRESENT`
    FOREIGN KEY (`Present_ID`)
    REFERENCES `DB3087534`.`gg_Interest` (`Present_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DEMAND_PRESENT`
    FOREIGN KEY (`Present_ID`)
    REFERENCES `DB3087534`.`gg_Demand` (`Present_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_OFFER_PRESENT`
    FOREIGN KEY (`Present_ID`)
    REFERENCES `DB3087534`.`gg_Offer` (`Present_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB3087534`.`gg_Present_has_Tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB3087534`.`gg_Present_has_Tags` ;

CREATE TABLE IF NOT EXISTS `DB3087534`.`gg_Present_has_Tags` (
  `Present_ID` INT NOT NULL,
  `Tag_ID` INT NOT NULL,
  PRIMARY KEY (`Present_ID`, `Tag_ID`),
  INDEX `Tag_IND` (`Tag_ID` ASC),
  INDEX `Present_IND` (`Present_ID` ASC),
  CONSTRAINT `FK_PRESENT_HAS_TAGS`
    FOREIGN KEY (`Present_ID`)
    REFERENCES `DB3087534`.`gg_Present` (`Present_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB3087534`.`gg_Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB3087534`.`gg_Tag` ;

CREATE TABLE IF NOT EXISTS `DB3087534`.`gg_Tag` (
  `Tag_ID` INT NOT NULL AUTO_INCREMENT,
  `Tag` VARCHAR(255) NOT NULL,
  INDEX `Tag_ID_IND` (`Tag_ID` ASC),
  PRIMARY KEY (`Tag_ID`),
  FULLTEXT INDEX `Tag_TXT` (`Tag` ASC),
  CONSTRAINT `FK_PRESENT_TAG`
    FOREIGN KEY (`Tag_ID`)
    REFERENCES `DB3087534`.`gg_Present_has_Tags` (`Tag_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
