-- MySQL Script generated by MySQL Workbench
-- 09/02/17 00:26:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema DB3087534
-- -----------------------------------------------------
USE `DB3087534` ;

-- -----------------------------------------------------
-- Table `gg_User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gg_User` ;

CREATE TABLE IF NOT EXISTS `gg_User` (
  `User_ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Zip_Code` VARCHAR(10) NOT NULL,
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC),
  PRIMARY KEY (`User_ID`),
  INDEX `Name_IND` (`Name` ASC),
  INDEX `Email_IND` (`Email` ASC),
  INDEX `Zip_Code_IND` (`Zip_Code` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gg_Present`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gg_Present` ;

CREATE TABLE IF NOT EXISTS `gg_Present` (
  `Present_ID` INT NOT NULL AUTO_INCREMENT,
  `User_ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(32000) NOT NULL,
  PRIMARY KEY (`Present_ID`),
  FULLTEXT INDEX `Description_TXT` (`Description` ASC),
  INDEX `User_IND` (`User_ID` ASC),
  INDEX `Name_IND` (`Name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gg_Demand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gg_Demand` ;

CREATE TABLE IF NOT EXISTS `gg_Demand` (
  `User_ID` INT NOT NULL,
  `Present_ID` INT NOT NULL,
  PRIMARY KEY (`User_ID`, `Present_ID`),
  INDEX `User_IND` (`User_ID` ASC),
  INDEX `Present_IND` (`Present_ID` ASC),
  CONSTRAINT `FK_USER_DEMAND`
    FOREIGN KEY (`User_ID`)
    REFERENCES `gg_User` (`User_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PRESENT_DEMAND`
    FOREIGN KEY (`Present_ID`)
    REFERENCES `gg_Present` (`Present_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gg_Offer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gg_Offer` ;

CREATE TABLE IF NOT EXISTS `gg_Offer` (
  `User_ID` INT NOT NULL,
  `Present_ID` INT NOT NULL,
  PRIMARY KEY (`User_ID`, `Present_ID`),
  INDEX `User_IND` (`User_ID` ASC),
  INDEX `Present_IND` (`Present_ID` ASC),
  CONSTRAINT `FK_USER_OFFER`
    FOREIGN KEY (`User_ID`)
    REFERENCES `gg_User` (`User_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PRESENT_OFFER`
    FOREIGN KEY (`Present_ID`)
    REFERENCES `gg_Present` (`Present_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
